apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpqe-metrics
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpqe-metrics
  template:
    metadata:
      labels:
        app: kpqe-metrics
    spec:
      serviceAccountName: kpqe-sa
      containers:
      - name: kpqe-metrics
        image: kpqe-metrics:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kpqe-metrics
  namespace: observability
spec:
  selector:
    app: kpqe-metrics
  ports:
    - port: 8000
      targetPort: 8000
